version: '2'

services:

  postgres:
    image: postgres:15.2-alpine
    ports: 
    - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust


  backend:
    build: .
    depends_on:
      - postgres
    ports: 
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/mode_modules
    command: npm run start
    environment:
      DATABASE_URL: postgresql://postgres:uGhJZTfX1cqcnMbSH4R9@containers-us-west-24.railway.app:6627/railway


    

